---
title: "Homework 4: Precipitation"
author: "David M. Kahler"
output: pdf_document
header-includes: 
      \usepackage{amsmath}
---
**CIVE 351: Water Resources Engineering**  
**Duquesne University**  

```{r include=FALSE}
library(ggplot2)
library(raster)
library(rgdal)
library(dplyr)
library(broom)
```

1. Show that the reciprocal distance method becomes an arithmetic mean if $b = 0$.  
2. Obtain precipitation data for Pittsburgh International Airport from NOAA.  Over the past few years, determine the average annual precipitation for the area in mm.  Please turn in a table that includes year, start and end dates, and annual precipitation; your average annual precipitation can be averaged at the bottom of your table.  
3. Using NASA's [Giovanni](https://giovanni.gsfc.nasa.gov/giovanni/), use a reasonable averaging area and estimate the annual precipitation with the Global Precipitation Measurement (GPM) tool.  Please turn in a figure with annual precipitation and table to justify your final answer.  (NB: You may have to create a login to obtain data)  
